New test to create l2vpns and check connectivity
atlanticwave-sdx/sdx-end-to-end-tests pull request #8
Opened 2024-11-25 14:51 UTC by gretelliz

Create a new tests on the L2VPN creation: 
- `test_060_create_and_delete_l2vpn`: Create 10 l2vpn between differnet endpoints of the topology, randomly remove 5 of them, and test the connectivity between then.

2024-11-27 15:19 UTC, italovalcy reviewed
Hi Gretel! Excellent pull request, very nice to see how this is progressing! One thing, though that I would like to require your help is: I see the testing is leveraging ping among switches to check connectivity, but I want to ask you to test connectivity using ping among hosts. Testing connectivity using switches will give you a false positive output because switches all run as process in the emulation host, so it will work as a ping to localhost

2024-11-29 23:38 UTC, gretelliz commented
Thank you very much @italovalcy. Please, note that I have made changes based on your comments.

2024-12-12 07:26 UTC, italovalcy requested changes
Hi Gretel, congratulations on the pull request adding this new test! Amazing to see how this is progressing! I made a few comments to contribute on the testing methodology, suggesting the removal of some sleeps and also changes on the execution order and formatting style. Please let me know what you think!

2024-12-12 07:26 UTC, italovalcy commented on tests/test_05_l2vpn.py
> +        time.sleep(30)
not necessary

2024-12-12 07:26 UTC, italovalcy commented on tests/test_05_l2vpn.py
> +        time.sleep(30)
not necessary

2024-12-12 21:58 UTC, gretelliz commented on tests/test_05_l2vpn.py
> +        time.sleep(30)
You're right, the comment is confusing. This is some time after removing a link.

2024-12-12 22:12 UTC, gretelliz commented
@italovalcy, thank you very much for your review and comments. Note that I have made a new push.

2024-12-17 18:16 UTC, italovalcy commented
> @italovalcy, thank you very much for your review and comments. Note that I have made a new push.

Hi Gretel, I'm still seeing some of the comments I made last review as pending. Are you still working on those adjustments?

2024-12-17 18:50 UTC, gretelliz commented
Hello @italovalcy. I don't have anything pending regarding this PR, I think I have covered all your recommendations.

2024-12-18 17:45 UTC, italovalcy commented on tests/test_05_l2vpn.py
> +        h1.cmd('ip addr add 10.1.1.1/24 dev vlan101')
Gretel, can you please update the IP address assigned to VLAN 101 to something different? Example: 10.1.2.1/24

2024-12-18 17:45 UTC, italovalcy commented on tests/test_05_l2vpn.py
> +        h8.cmd('ip addr add 10.1.1.8/24 dev vlan101')
same here

2024-12-20 22:39 UTC, gretelliz commented
@italovalcy, note that the last two asserts in this last commit are commented out, they fail. Should that be the behavior?

2025-01-17 14:30 UTC, italovalcy approved these changes
Great improvement, Gretel! I'm marking this PR as approved!

2025-01-17 16:03 UTC, gretelliz commented
@italovalcy, thank you!

2025-01-17 16:03 UTC, merged