E2e tests
atlanticwave-sdx/sdx-end-to-end-tests pull request #9
Opened 2024-12-04 03:22 UTC by gretelliz

This PR is to test the return codes.

2024-12-04 16:40 UTC, italovalcy reviewed
Hi @gretelliz as we discussed on today's meeting, can you please refactor this test and split the return code validation function into a new file, let's say `test_06_l2vpn_return_codes.py` ?

2024-12-09 21:15 UTC, gretelliz commented
Sure @italovalcy, please note that I did what you suggested in the last commit.

2024-12-12 07:30 UTC, italovalcy commented
Hi Gretel I see that some of the changes described on this PR are also listed on PR #8. I believe that is because the target branch here is also main, while the branch you are using here was based on the previous one from PR #8. I will change the target branch here to facilitate the review, okay?

2024-12-12 07:38 UTC, italovalcy requested changes
Hi Gretel, amazing to see how this is progressing well! Congratulations! I have two comments for you please to consider:
1. Can you please make a slight change on the name of the tests to add a very short description about what the test is doing? I added suggestions for the two first ones, but please also apply this change on the others!
2. Can you please run a pylint or similar on this code? I see a few commas on the wrong place and pylint will help you identify some improvements on the formatting style.

2024-12-12 07:38 UTC, italovalcy commented on tests/test_06_l2vpn_return_codes.py
> +            ],}
```suggestion
            ]
        }
```

2024-12-12 07:38 UTC, italovalcy commented on tests/test_06_l2vpn_return_codes.py
> +    def test_010_code201(self):
```suggestion
    def test_010_create_l2vn_with_vlan_id_code201(self):
```

2024-12-12 07:38 UTC, italovalcy commented on tests/test_06_l2vpn_return_codes.py
> +    def test_011_code201(self):
```suggestion
    def test_011_create_l2vn_with_vlan_any_code201(self):
```

2024-12-12 07:38 UTC, italovalcy commented on tests/test_06_l2vpn_return_codes.py
> +            ],}
```suggestion
            ]
        }
```

2024-12-12 07:39 UTC, italovalcy commented on tests/test_06_l2vpn_return_codes.py
> +                {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50","vlan": "150",},
```suggestion
                {"port_id": "urn:sdx:port:ampath.net:Ampath3:50","vlan": "100"},
                {"port_id": "urn:sdx:port:tenet.ac.za:Tenet03:50","vlan": "150"},
```

2024-12-13 19:53 UTC, gretelliz commented
Thank you for your review @italovalcy.

2024-12-17 18:14 UTC, italovalcy approved these changes
Very nicely done, Gretel! LGTM!

2024-12-17 18:47 UTC, merged